name: Condition
on: [ push ]
env:
  PROTECTED_BRANCHES: |
    [
      "dev",
      "main"
    ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        uses: tj-actions/branch-names@v8
        id: branch-names
      - name: Run doctest
        run: |
          pytest --doctest-modules .
