name: Condition
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    env:
        PROTECTED_BRANCHES: |
          [
            "dev",
            "main"
          ]
    steps:
      - name: Get branch names
        uses: tj-actions/branch-names@v8
        id: branch-names
      - name: Push changes
        if: true && ${{ !contains(env.PROTECTED_BRANCHES, steps.branch-names.outputs.current_branch) }}
        run: |
          echo "executed"
