name: Condition
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        uses: tj-actions/branch-names@v8
        id: branch-names
      - name: Push changes
        if: contains(fromJSON('["main", "dev"]'), steps.branch-names.outputs.current_branch)
        run: |
          echo "executed"
