name: Lint
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3
        
      - name: Check files using the black formatter
        id: action_black
        uses: psf/black@stable
        with:
          options: "--pyi --safe --verbose"
          src: "./python"
          jupyter: true
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
          
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
        
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          BRANCH=$(git branch --show-current)
          echo $BRANCH
          git config --global user.name 'Chaminda1993'
          git config --global user.email 'c771904768@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout $BRANCH
          git commit -am "Automated changes"
          git push
