name: Lint
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3
        
      - name: Check files using the black formatter
        id: action_black
        uses: psf/black@stable
        with:
          options: "--check --code --verbose"
          src: "./python"
          jupyter: true
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
          
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
        
      # - name: Push changes
        # if: steps.action_black.outputs.is_formatted == 'true'
        # run: |
          # git config --global user.name 'Peter Evans'
          # git config --global user.email 'peter-evans@users.noreply.github.com'
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # git commit -am "Automated changes"
          # git push
