name: Lint
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code...
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Check files using the Ruff linter
        uses: chartboost/ruff-action@v1
